language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t anirudhan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run anirudhan/react-test npm test -- --coverage
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t anirudhan/multi-client ./client
  - docker build -t anirudhan/multi-nginx ./nginx
  - docker build -t anirudhan/multi-server ./server
  - docker build -t anirudhan/multi-worker ./worker
